### ISSUE TITLE
Agent doesn't move when called over Transform and Reposition

### ISSUE THREAD

**Issue by JD-ETH** [MIT-TESSE/tesse-interface#4]
Can't make the agent move, but receive observation normally. I call the simulation and setup communication as following: 
```
from tesse_gym.tasks.goseek.goseek_full_perception import GoSeekFullPerception, decode_observations
from tesse_gym import get_network_config
from tesse_gym.core.utils import set_all_camera_params
env = GoSeekFullPerception(
                str(filename),
                network_config=get_network_config(worker_id=0),
                n_targets=20,
                episode_length=50,
                scene_id=0,
                target_found_reward=2,
                step_rate=20,
                init_hook=set_all_camera_params
            )
from tesse.env import Env
from tesse.msgs import *
comm = Env()
```
I have then tried the following calls to make the agent move from its initial location: 
```
obs = env.step(0)
env.apply_action(0,0.5,0)
comm.send(Transform(-1, 0, 0)) 
comm.send(Reposition(0, .5, 2, 0, 0, 0, 0))
```
I have tried the following calls to observe the updated position with the following: 
```
env.render()
env._update_pose(env.observe().metadata)
env.get_pose()
```
But the agent never leaves its original location [0,0,0]. What am I missing? How do you examine the comm.send() has succeeded in your notebook example? The training with `ppo2` runs fine, but I can't use the interface to make the move. Other requests seem to work, such as getting observations, changing camera configuration, resetting.

**Comment by ZacRavichandran** [comment]
Could you try two things?

1. Try loading `scene_id` = 1-5, those are the available scenes (you can find the layouts [here](https://github.com/MIT-TESSE/goseek-challenge/blob/0.1.1-SNAPSHOT/doc/details.md#scenes)).

2. When using `tesse-interface` to control the agent, try using `StepWithTransform` instead of `Transform`.  Setting `step_rate` puts the simulator in [step mode](https://github.com/MIT-TESSE/tesse-core#timing-modes) which synchronizes requests between the client and simulator. `StepWithTransform` handles that logic. (`GoSeekFullPerception.apply_action` will switch between these two commands depending on the mode).

**Comment by JD-ETH** [comment]
Item 1 fixed this. Thanks a lot!
